lunar-linux/moonbase-xorg

lib/mesa-lib/BUILD
lib/mesa-lib/CONFIGURE

- force egl, xa, gles1, gles2 and gbm. They shouldn't break anything
- add osmesa. This is a standalone addition some stuff already depends on

mesa-lib: drastically simplify CONFIGURE

---

lib/mesa-lib/DEPENDS

WARNING: unrecognized options: --enable-kdrive-evdev, --disable-glamor, --enable-libunwind, --enable-wayland, --without-xmlto
Removing these, wayland is handled in the BUILD.

mesa-lib: The configure phase shows the following;

---

fontconfig/DETAILS

2.12.0 doesn't seem to build with gcc 7.2.0 anyway.

fontconfig: Version bumped to 2.12.6.

---

driver/xf86-video-amdgpu/BUILD

added -fcommon to BUILD, to compile with GCC 10.
This should be considered temporary - a patch or version bump will probably be made quickly.

xf86-video-amdgpu GCC fix

---

app/xauth/DETAILS

Upstream went with xz instead of bzip2.

xauth: version bumped to 1.1.2

---

app/setxkbmap/BUILD
app/setxkbmap/DEPENDS
app/setxkbmap/DETAILS

Upstream also changed the bzip2 archive for the xz format here.

setxkbmap: version bumped to 1.3.3

---

app/mkfontscale/BUILD
app/mkfontscale/DEPENDS
app/mkfontscale/DETAILS

Upstream changed bzip2 archive to xz.

mkfontscale: version bumped to 1.2.2

---

app/iceauth/DETAILS

Upstream changed archive format from bzip2 to xz. gzip still available.

iceauth: version bumped to 1.0.9

---

app/bitmap/DETAILS

Upstream changed from bz2 archive to xz.

bitmap: version bumped to 1.1.0

---

app/appres/DETAILS

Upstream changed tarball compression from bz2 to xz

appres: version bumped to 1.0.6

---

driver/xf86-video-dummy/DETAILS

Upstream changed archive format from bz2 to xz.

xf86-video-dummy: version bumped to 0.4.0

---

font/font-util/DETAILS

Upstream went from bz2 to xz here too.

font-util: version bumped to 1.3.3

---

font/encodings/DETAILS

Upstream changed from bz2 to xz for tarball compression. 
Also the gz format remains available.

encodings: version bumped to 1.0.6

---

utils/imake/DETAILS

Upstream changed from bz2 to xz, gz still available.

imake: version bumped to 1.0.9

---

app/rgb/DETAILS

Archive type also changed from bz2 to xz here.

rgb: version bumped to 1.1.0

---

driver/xf86-video-intel/DETAILS
driver/xf86-video-intel/patch.d/xf86-video-intel-3.9.7-new_naming.patch

The xorg-server devs renamed slave_dst to secondary_dst and master_pixmap to primary_pixmap.

xf86-video-intel: add patch for xorg variable renaming

---

lib/libXpm/DETAILS

This release fixes CVE-2023-43788 and CVE-2023-43789 , see https://lists.x.org/archives/xorg/2023-October/061506.html for more details.

libXpm: version bumped to 3.5.17, security fix

---

lib/libX11/DETAILS

This release fixes CVE-2023-43785 CVE-2023-43786 and CVE-2023-43787 , see https://lists.x.org/archives/xorg/2023-October/061506.html

libX11: version bumped to 1.8.7, security fix

---

crater/README

The creation of this file is mostly justified to keep the directory present even if there's no modules in it. And it doesn't hurt to add a little description to it :)

xorg/crater: add a basic README

---

doc/xorg-sgml-doctools/BUILD
doc/xorg-sgml-doctools/DETAILS
doc/xorg-sgml-doctools/PRE_BUILD

The mailinglist email says that the autoconf build system will be removed in future releases, so switch to meson now.

xorg-sgml-doctools: version bumped to 1.12.1 + switch to meson

---

lib/libepoxy/DEPENDS

/usr/include/epoxy/egl.h is required by xorg-server and is only generated when gegl is installed, so make it mandatory as well as libglvnd and libX11 as suggested by Ratler.

libepoxy: add required deps (gegl, libglvnd and libX11)

---

xorg-server/DETAILS

Fixes CVE-2024-9632: Heap-based buffer overflow privilege escalation in _XkbSetCompatMap

xorg-server: version bumped to 21.1.14 (security fix)

---

xorg-server/DEPENDS

So I'm testing the deployment of a graphical env in Qemu... the configuring fails with missing libXdmcp, so add it to the DEPENDS.

xorg-server: add a missing dependency

---

lib/mesa-lib/POST_INSTALL

This problem was found during a deployment test of a graphical env in a VM. The xorg-server module would fail with a missing epoxy/glx.h header, which comes from libepoxy being built with mesa-lib already installed.

mesa-lib: fix first-time installs
